name: Sync to Hugging Face Hub

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git remote add space https://Ansh1271:$HF_TOKEN@huggingface.co/spaces/Ansh31/bert-sentiment-analyzer-app
          git push --force space main
